name: Personal portfolio deploy workflow

on:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: '19.x'
      - run: npm ci
      - run: npm run build
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: 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
