name: Personal portfolio deploy workflow

on:
  schedule:
    # every 24 hours
    - cron: '0 */24 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '19.x'
      - run: npm ci
      - run: npm run build
      - run: gh-pages -d build
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: 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
